name: 🐛 Bug Report
description: File a bug report to help us improve
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Affected Version
      description: What version of scripts are you running?
      placeholder: "v4.3.0"
    validations:
      required: true
  - type: dropdown
    id: script
    attributes:
      label: Script
      multiple: true
      options:
        - ci/install-shellcheck.sh
        - ci/install-shellspec.sh
        - ci/jelastic/deploy.sh
        - ci/jelastic/utils.sh
        - qa/run-shellcheck.sh
        - qa/run-shellcheck-pull-hooks.sh
        - qa/run-shellspec-if-installed.sh
        - releasing/common-constants.source.sh
        - releasing/deduce-next-version.source.sh
        - releasing/pre-release-checks-git.sh
        - releasing/prepare-files-next-dev-cycle.sh
        - releasing/prepare-next-dev-cycle-template.sh
        - releasing/release-files.sh
        - releasing/release-template.sh
        - releasing/sbt-publish-to-sonatype.sh
        - releasing/sneak-peek-banner.sh
        - releasing/toggle-sections.sh
        - releasing/update-version-common-steps.sh
        - releasing/update-version-README.sh
        - releasing/update-version-scripts.sh
        - releasing/update-version-issue-templates.sh
        - utility/array-utils.sh
        - utility/ask.sh
        - utility/checks.sh
        - utility/cleanups.sh
        - utility/date-utils.sh
        - utility/execute-if-defined.sh
        - utility/git-utils.sh
        - utility/gpg-utils.sh
        - utility/http.sh
        - utility/io.sh
        - utility/log.sh
        - utility/parse-args.sh
        - utility/parse-commands.sh
        - utility/parse-utils.sh
        - utility/parse-fn-args.sh
        - utility/recursive-declare-p.sh
        - utility/replace-snippet.sh
        - utility/replace-help-snippet.sh
        - utility/string-utils.sh
        - utility/source-once.sh
        - utility/update-bash-docu.sh
        - setup.sh
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the problem?
    validations:
      required: false
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
